// AUTO-GENERATED by scripts/build-sites.mjs from the sites/ folder. Do not edit by hand.
const generatedSites = [
  {
    "name": "Name",
    "year": 2024,
    "website": "https://sayfern.ca"
  }
];

export default generatedSites;
