// Combines every sites/*.json file into js/generated_sites.js.
// Entries are ordered by when their file was first added to the current branch
// (the merge commit for a PR), so whoever's PR is merged first shows up first.
// Run from the repo root: node scripts/build-sites.mjs

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";

const SITES_DIR = "sites";
const OUTPUT = "js/generated_sites.js";

// Map each sites/ file to the timestamp of the first-parent commit that added it.
// --first-parent makes a merged PR count at merge time rather than at its own commit times.
function addedTimes() {
  let log;
  try {
    log = execFileSync(
      "git",
      ["log", "--first-parent", "--diff-filter=A", "--no-renames", "--name-only", "--format=@%ct", "--", `${SITES_DIR}/`],
      { encoding: "utf8" }
    );
  } catch {
    // No git history available (e.g. some preview builds): fall back to filename order
    console.warn("git log failed, ordering by filename");
    return {};
  }
  const times = {};
  let current = 0;
  for (const line of log.split("\n")) {
    if (line.startsWith("@")) {
      current = Number(line.slice(1));
    } else if (line.trim()) {
      // git log is newest first, so keep overwriting to end on the oldest add
      times[line.trim()] = current;
    }
  }
  return times;
}

const times = addedTimes();
const errors = [];

const files = readdirSync(SITES_DIR).filter((f) => f.endsWith(".json"));

const entries = files.map((file) => {
  const path = `${SITES_DIR}/${file}`;
  let site;
  try {
    site = JSON.parse(readFileSync(path, "utf8"));
  } catch (e) {
    errors.push(`${path}: invalid JSON (${e.message})`);
    return null;
  }
  for (const key of ["name", "year", "website"]) {
    if (!site[key]) errors.push(`${path}: missing "${key}"`);
  }
  const { name, year, website, alias } = site;
  const clean = { name, year: Number(year), website };
  if (alias) clean.alias = alias;
  // Files not committed yet (local runs) sort last
  return { file, time: times[path] ?? Infinity, site: clean };
});

if (errors.length) {
  console.error(errors.join("\n"));
  process.exit(1);
}

entries.sort((a, b) => a.time - b.time || a.file.localeCompare(b.file));

const output =
  "// AUTO-GENERATED by scripts/build-sites.mjs from the sites/ folder. Do not edit by hand.\n" +
  "const generatedSites = " +
  JSON.stringify(entries.map((e) => e.site), null, 2) +
  ";\n\nexport default generatedSites;\n";

writeFileSync(OUTPUT, output);
console.log(`Wrote ${entries.length} site(s) to ${OUTPUT}`);
